title: My Website
email: farhanfs.008@gmail.com
description: JSON Wordle
baseurl: "/"
url: "https://farhanfs008.github.io/json-wordle/"
permalink: /:title/
theme: minima
collections:
  projects:
    output: true
    permalink: /projects/:title/
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      title: "JSON Wordle"
      description: "JSON Wordle"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
